//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCK_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class klub
    {
        public klub()
        {
            this.zawodnicy = new HashSet<zawodnicy>();
        }
    
        public int id_klub { get; set; }
        public string nazwa { get; set; }
        public int majatek { get; set; }
        public string path { get; set; }
    
        public virtual ICollection<zawodnicy> zawodnicy { get; set; }
        public override string ToString()
        {
            return nazwa;
        }
    }
}
