//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCK_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string login { get; set; }
        public string haslo { get; set; }
        public int wiek { get; set; }
    }
}
