//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCK_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class zawodnicy
    {
        public int id_zawodnik { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public int wartosc { get; set; }
        public string pozycja { get; set; }
        public int id_klub { get; set; }
    
        public virtual klub klub { get; set; }
    }
}
